openapi: "3.0.2"

info:
  title: "Address API"
  description: "Address API"
  version: "1.0"

servers:
  - url: http://localhost:8000

paths:
  "/api/contacts/{contactId}/addresses":
    post:
      description: "Create contact address"
      parameters:
        - in: path
          name: contactId
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                street:
                  type: string
                city:
                  type: string
                province:
                  type: string
                country:
                  type: string
                postalCode:
                  type: string
      responses:
        "201":
          description: "Success create contact address"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                  errors:
                    type: object

    get:
      description: "Get list contact addresses"
      parameters:
        - in: path
          name: contactId
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: "Success get list contact addresses"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                        type: object
                        properties:
                          id:
                            type: number
                          street:
                            type: string
                          city:
                            type: string
                          province:
                            type: string
                          country:
                            type: string
                          postalCode:
                            type: string
                  errors:
                    type: object

  "/api/contacts/{contactId}/addresses/{addressId}":
    get:
      description: "Get contact address details"
      parameters:
        - in: path
          name: contactId
          schema:
            type: number
          required: true
        - in: path
          name: addressId
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: "Success get contact address details"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      street:
                        type: string
                      city:
                        type: string
                      province:
                        type: string
                      country:
                        type: string
                      postalCode:
                        type: string
                  errors:
                    type: object
    put:
      description: "Update contact address"
      parameters:
        - in: path
          name: contactId
          schema:
            type: number
          required: true
        - in: path
          name: addressId
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        description: "Update existing contact address"
        content:
          application/json:
            schema:
              type: object
              properties:
                street:
                  type: string
                city:
                  type: string
                province:
                  type: string
                country:
                  type: string
                postalCode:
                  type: string
      responses:
        "200":
          description: "Success update contact address"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                  errors:
                    type: object
    delete:
      description: "Delete contact address"
      parameters:
        - in: path
          name: contactId
          schema:
            type: number
          required: true
        - in: path
          name: addressId
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: "Success delete contact address"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                  errors:
                    type: object
