openapi: 3.0.2

info:
  title: "Contact API"
  description: "Contact API"
  version: "1.0"

servers:
  - url: http://localhost:8000

paths:
  "/api/contacts":
    post:
      description: "Create new contact"
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        "200":
          description: "Success create contact"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                  errors:
                    type: object
    get:
      description: "Search contact"
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: phone
          schema:
            type: string
        - in: query
          name: email
          schema:
            type: string
        - in: query
          name: size
          schema:
            type: number
        - in: query
          name: page
          schema:
            type: number
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: "Success search contacts"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                        type: object
                        properties:
                          id:
                            type: string
                          firstName:
                            type: string
                          lastName:
                            type: string
                          email:
                            type: string
                          phone:
                            type: string
                  errors:
                    type: object
                  meta:
                    type: object

  "/api/contacts/{id}":
    put:
      description: "Update contact"
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        "200":
          description: "Success update contact"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                  errors:
                    type: object
    get:
      description: "Get contact"
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: "Success get contact"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      firstName:
                          type: string
                      lastName:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                  errors:
                    type: object
    delete:
      description: "Delete contact"
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: "Success delete contact"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                  errors:
                    type: object
