openapi: 3.0.2

info:
  title: "Contact API"
  description: "Contact API"
  version: "1.0"

servers:
  - url: http://localhost:8000

paths:
  "/api/contacts":
    post:
      description: "Create new contact"
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        "201":
          description: "Success create contact"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                  errors:
                    type: object
        "400":
          description: "Validation error response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
              examples:
                "firstName field invalid error":
                  value:
                    errors:
                      firstName:
                        - "firstName is required"
                        - "firstName max 100 character length"
                "lastName field invalid error":
                  value:
                    errors:
                      lastName:
                        - "lastName max 100 character length"
                "email field invalid error":
                  value:
                    errors:
                      email:
                        - "email must be valid email format"
                "phone field invalid error":
                  value:
                    errors:
                      phone:
                        - "phone max 20 character length"
                "Combination error 1":
                  value:
                    errors:
                      firstName:
                        - "firstName is required"
                        - "firstName max 100 character length"
                      email:
                        - "email must be valid email format"
                "Combination error 2":
                  value:
                    errors:
                      lastName:
                        - "lastName max 100 character length"
                      email:
                        - "email must be valid email format"
                      phone:
                        - "phone max 20 character length"
        "401":
          description: "Unauthenticated error"
          content:
            application/json:
              examples:
                "Unauthenticated user cannot access the resource":
                  value:
                    errors:
                      message: "Unauthorized."

    get:
      description: "Search contact"
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: phone
          schema:
            type: string
        - in: query
          name: email
          schema:
            type: string
        - in: query
          name: size
          schema:
            type: number
        - in: query
          name: page
          schema:
            type: number
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: "Success search contacts"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                        type: object
                        properties:
                          id:
                            type: string
                          firstName:
                            type: string
                          lastName:
                            type: string
                          email:
                            type: string
                          phone:
                            type: string
                  errors:
                    type: object
                  meta:
                    type: object
        "401":
          description: "Unauthenticated error"
          content:
            application/json:
              examples:
                "Unauthenticated user cannot access the resource":
                  value:
                    errors:
                      message: "Unauthorized."

  "/api/contacts/{id}":
    put:
      description: "Update contact"
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        "200":
          description: "Success update contact"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                  errors:
                    type: object
        "400":
          description: "Validation error response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
              examples:
                "firstName field invalid error":
                  value:
                    errors:
                      firstName:
                        - "firstName is required"
                        - "firstName max 100 character length"
                "lastName field invalid error":
                  value:
                    errors:
                      lastName:
                        - "lastName max 100 character length"
                "email field invalid error":
                  value:
                    errors:
                      email:
                        - "email must be valid email format"
                "phone field invalid error":
                  value:
                    errors:
                      phone:
                        - "phone max 20 character length"
                "Combination error 1":
                  value:
                    errors:
                      firstName:
                        - "firstName is required"
                        - "firstName max 100 character length"
                      email:
                        - "email must be valid email format"
                "Combination error 2":
                  value:
                    errors:
                      lastName:
                        - "lastName max 100 character length"
                      email:
                        - "email must be valid email format"
                      phone:
                        - "phone max 20 character length"
        "401":
          description: "Unauthenticated error"
          content:
            application/json:
              examples:
                "Unauthenticated user cannot access the resource":
                  value:
                    errors:
                      message: "Unauthorized."
    get:
      description: "Get contact"
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: "Success get contact"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      firstName:
                          type: string
                      lastName:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                  errors:
                    type: object
        "404":
          description: "Not found error"
          content:
            application/json:
              examples:
                "Not found response":
                  value:
                    errors:
                      message: "Resource not found."
        "401":
          description: "Unauthenticated error"
          content:
            application/json:
              examples:
                "Unauthenticated user cannot access the resource":
                  value:
                    errors:
                      message: "Unauthorized."
    delete:
      description: "Delete contact"
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: "Success delete contact"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                  errors:
                    type: object
        "404":
          description: "Not found error"
          content:
            application/json:
              examples:
                "Not found response":
                  value:
                    errors:
                      message: "Resource not found."
        "401":
          description: "Unauthenticated error"
          content:
            application/json:
              examples:
                "Unauthenticated user cannot access the resource":
                  value:
                    errors:
                      message: "Unauthorized."
